WIP: Pouta network documentation
CSCfi/csc-user-guide pull request #1628
Opened 2023-04-03 11:45 UTC by Socuz

https://csc-guide-preview.rahtiapp.fi/origin/pouta-network/cloud/pouta/networking/

2023-04-03 13:20 UTC, lvarin requested changes
Looks good, only minor comments

2023-04-03 13:20 UTC, lvarin commented on docs/cloud/pouta/networking.md
> +In the situation that your project is missing a default network you will not be able to create a virtual machine. And if you are missing a router, you will not be able to assign ports in your machine
It may be useful to rewrite this so the concept of "port" is explained.

2023-04-03 13:20 UTC, lvarin commented on docs/cloud/pouta/networking.md
> +**Availabity Zone Hints** - Select your availability zone.
There is currently only one availability zone in our OpenStack

2023-04-04 05:33 UTC, Socuz commented
Thank you Alvaro, I updated following your recommendations.

2023-04-19 05:51 UTC, lvarin commented on docs/cloud/pouta/networking.md
> +If you want to access your instances from the external, you need to associate a [floating IP](launch-vm-from-web-gui.md#post-creation-step).
```suggestion
If you want to access your instances from an external network, you need to associate a [floating IP](launch-vm-from-web-gui.md#post-creation-step).  
```

2023-04-19 05:52 UTC, lvarin requested changes
LGTM, only the minor suggestion that is in the comments.

2023-04-19 06:45 UTC, lvarin approved these changes

2023-04-19 06:46 UTC, merged