Create pennylane.md
CSCfi/csc-user-guide pull request #1882
Opened 2023-11-15 13:44 UTC by TheKharleeci

## Proposed changes
 - add documentation for using Pennylane on Lumi
 - here is a link to the [preview page](https://csc-guide-preview.rahtiapp.fi/origin/ft-add-pennylane-app/).

## Checklist before requesting a review

- [x] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [x] My pull request passes all tests.
- [x] I have included a link to the appropriate [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) (select your branch from the list).

2023-11-15 14:08 UTC, JMuff22 commented on docs/apps/pennylane.md
> +module load pennylane-lightning-kokkos
What about `module use ...` ?

2023-11-15 14:10 UTC, JMuff22 commented on docs/apps/pennylane.md
> +PennyLane is an open-source software framework for quantum machine learning,
Perhaps we should emphasize that this is a GPU enabled piece of software?

2023-11-15 14:11 UTC, JMuff22 commented on docs/apps/pennylane.md
> +| 0.33.0  | `pennylane-lightning-kokkos/0.33.0`  | X     | default version |
I believe `pennylane-lightning-kokkos>0.32` is deprecated. The kokkos accelerated part of pennylane-lightning is now provided through `pennylane-lightning>=0.33` https://github.com/PennyLaneAI/pennylane-lightning/releases/tag/v0.33.0

2023-11-15 14:21 UTC, JMuff22 commented on docs/apps/pennylane.md
> +| 0.33.0  | `pennylane-lightning-kokkos/0.33.0`  | X     | default version |
I think so. Yeah it's confusing. If 0.33 works well then 0.32 and 0.31 could be removed?

2023-11-15 14:37 UTC, joonas-somero commented on docs/apps/pennylane.md
> +    ```
If you're using the single tab only to render a title for the code block, I'd suggest `title="LUMI"`.

```suggestion
```bash title="LUMI"
#!/bin/bash
#SBATCH --account=<project>
#SBATCH --partition=dev-g
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=128G
#SBATCH --time=0:10:00
#SBATCH --gpus=1
#SBATCH --job-name=pennylane-example

# setting environment variables to specify how the OpenMP threads in a program are bound to processors
export OMP_PROC_BIND=spread  
export OMP_PLACES=threads

module load pennylane-lightning-kokkos
python3 simple_test.py
```
```

2023-11-21 08:24 UTC, JMuff22 requested changes

2023-11-21 08:24 UTC, JMuff22 commented on docs/apps/pennylane.md
> +PennyLane is an open-source GPU-enabled software framework for quantum machine learning,
Pennylane is an open-source cross-platform Python library for quantum machine learning, quantum chemistry and quantum computing. Pennylane-lightning is a high-performance state-vector simulator for Pennylane. It is currently GPU enabled through the [Kokkos](https://kokkos.github.io/kokkos-core-wiki/index.html) framework on LUMI.

2023-11-21 08:26 UTC, JMuff22 commented on docs/apps/pennylane.md
> +- [Pennylane documentation](https://docs.pennylane.ai/en/stable/code/qml.html)
Add `lightning.kokkos` documentation? https://docs.pennylane.ai/projects/lightning/en/stable/lightning_kokkos/device.html or https://docs.pennylane.ai/projects/lightning/en/stable/

2023-11-21 20:34 UTC, JMuff22 approved these changes
LGTM! Thanks for the changes

2023-11-22 07:31 UTC, rkronberg commented
Nice! Just a quick comment, the example batch script is claimed to reserve one GPU and _two_ CPU cores. However, I can see only one being requested? Or does this imply virtual cores (i.e. multi-threading)? Maybe clarify still that?

2023-11-22 07:57 UTC, JMuff22 commented on docs/apps/pennylane.md
> +export OMP_PROC_BIND=spread
If the environment variables for OpenMP are set, this implies that the Kokkos plugin was built with `-DKokkos_ENABLE_OPENMP=ON"` . Perhaps this should be specified. Also whilst many [resources](https://eurotug.github.io/assets/2023_eurotug_slides/KokkosTutorial_EuroTUG_2023_Day1.pdf) online recommend using these environment variables with Kokkos, unless we have explicitly tested their performance on LUMI, I suggest we exclude them.

2023-11-22 10:40 UTC, merged