nexcloud and encryotion
CSCfi/csc-user-guide pull request #1996
Opened 2024-02-15 12:41 UTC by kkmattil

## Proposed changes

Briefly describe the changes you've made here. Remember to add a link to the [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) of your branch.

## Checklist before requesting a review

- [ ] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [ ] My pull request passes all tests.
- [ ] I have included a link to the appropriate [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) (select your branch from the list).

2024-02-15 13:29 UTC, gitjopa approved these changes

2024-02-16 08:43 UTC, joonas-somero requested changes
There are no integration tests for branches on forks.

2024-02-16 09:59 UTC, kkmattil commented
so what is needed?

2024-02-16 10:32 UTC, joonas-somero commented
> so what is needed?

The source branch needs to be a branch of _this_ repository i.e. [CSCfi/csc-user-guide](https://github.com/CSCfi/csc-user-guide) and not a branch of a completely different repository such as [kkmattil/csc-user-guide](https://github.com/kkmattil/csc-user-guide) or for example [joonas-somero/csc-user-guide](https://github.com/joonas-somero/csc-user-guide).

2024-02-20 08:18 UTC, closed without merging