Rahti1 templates
CSCfi/csc-user-guide pull request #2080
Opened 2024-05-07 11:03 UTC by trispera

## Proposed changes

Publish a CSCfi repo with some of the Rahti 1 templates.
Add a link in the documentation

https://csc-guide-preview.rahtiapp.fi/origin/rahti1-templates/cloud/rahti2/catalog-docs/

## Checklist before requesting a review

- [x] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [x] My pull request passes all tests.
- [x] I have included a link to the appropriate [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) (select your branch from the list).

2024-05-08 10:39 UTC, lvarin commented on docs/cloud/rahti2/catalog-docs.md
> +    Most of the previous templates have been migrating to Helm Charts for Rahti 2. If you want to use a template from Rahti 1 on Rahti 2, you can find the repo at this [link](https://github.com/CSCfi
```suggestion
    Most of the previous templates have been migrated to Helm Charts for Rahti 2. If you want to use a Rahti 1 template on Rahti 2, you can find the repo at this [link](https://github.com/CSCfi/rahti-1-templates).  
```

2024-05-08 10:40 UTC, lvarin requested changes
small reword

2024-05-16 05:11 UTC, trispera commented
Suggestions committed

2024-05-17 10:25 UTC, lvarin approved these changes
LGTM

2024-05-17 10:45 UTC, merged