Added a note about privileges to Pukki's PSQL page, fixed some typos
CSCfi/csc-user-guide pull request #2087
Opened 2024-05-09 20:53 UTC by mattikan

## Proposed changes

Added a note about privileges on Pukki's PSQL page, since there was some confusion about those discussed internally recently

## Checklist before requesting a review

- [ ] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [ ] My pull request passes all tests.
- [ ] I have included a link to the appropriate [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) (select your branch from the list).

2024-05-10 07:57 UTC, oscarkraemer requested changes
- The section `How is DBaaS PostgreSQL different from normal PostgreSQL` should probably be rethought. 

It would probably be a good idea to add a section where we write two examples
- How to create a `read-only` role that have access to a specific table
- How to create a `read-only` role  that have access to all tables in specific schema.

I think it is important that we help users to make better decisions. By ensuring that our most novice users have decent documentation we will allow our users to be more empowered witch means that we will not need to spend less time answering simple tickets and allows us to focus on our main work.

2024-05-10 07:57 UTC, oscarkraemer commented on docs/cloud/dbaas/cli.md
>  Give database access to an existing user.
I think we should remove the `access` commands from `cli.md` and move it to `postgresql.md` and mention the schema specifically.

2024-05-22 11:17 UTC, oscarkraemer commented
This change looks good to me.

2024-05-23 11:08 UTC, lvarin commented on docs/cloud/dbaas/cli.md
> -openstack database user grant access $INSTNACE_ID $USER_NAME $DATABASE_NAME
There is a typo on instance variable

2024-05-23 11:08 UTC, lvarin commented on docs/cloud/dbaas/cli.md
> -openstack database user revoke access $INSTNACE_ID $USER_NAME $DATABASE_NAME
Same typo

2024-05-23 11:11 UTC, lvarin approved these changes
LGTM

2024-05-23 11:18 UTC, oscarkraemer approved these changes
I think I have now accepted some changes.

2024-05-23 11:19 UTC, merged