Update guide_for_teachers.md
CSCfi/csc-user-guide pull request #2116
Opened 2024-06-07 12:20 UTC by katrite

## Proposed changes

Briefly describe the changes you've made here. Remember to add a link to the [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) of your branch.

## Checklist before requesting a review

- [ ] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [ ] My pull request passes the automated tests. (If not, visit [pull requests at Travis CI](https://app.travis-ci.com/github/CSCfi/csc-user-guide/pull_requests) and have a look at the job log.)
- [ ] I have included a link to the appropriate [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) (select your branch from the list).

2024-06-25 11:26 UTC, rkronberg commented
Ping @tourunen :) Would you have time to check this?

2024-06-27 05:29 UTC, tourunen requested changes

2024-06-27 05:29 UTC, tourunen commented on docs/cloud/csc_notebooks/guide_for_teachers.md
> -* A place to upload the Docker image, for example DockerHub or Quay.io.
IMO DockerHub is a valid place to host images, we should leave it.

2024-06-27 05:29 UTC, tourunen commented on docs/cloud/csc_notebooks/guide_for_teachers.md
> -    * [Rocker images](https://hub.docker.com/u/rocker) for different RStudio set-ups.
To me it looks like Rocker project still hosts images on DockerHub as the primary source, and the other provided registry is GitHub container registry. 

https://rocker-project.org/images/versioned/r-ver.html#quick-reference

2024-06-27 05:29 UTC, tourunen commented on docs/cloud/csc_notebooks/guide_for_teachers.md
> -To build custom R images, you do not need to start from scratch. Many pre-built R images are already available in docker registries. Especially, the [rocker project](https://github.com/rocker-org/roc
I think the old text is still fine.

2024-09-03 11:37 UTC, rkronberg commented
Closing this PR based on comments by @tourunen (old text still ok and relevant).

2024-09-03 11:37 UTC, closed without merging