WIP: Vol snap shot
CSCfi/csc-user-guide pull request #2147
Opened 2024-07-08 12:34 UTC by vartikashah

## Proposed changes

Add Volume snap shot [preview page](https://csc-guide-preview.rahtiapp.fi/origin/vol-snap-shot/cloud/rahti2/storage/).

https://csc-guide-preview.rahtiapp.fi/origin/vol-snap-shot/cloud/rahti2/storage/
https://csc-guide-preview.rahtiapp.fi/origin/vol-snap-shot/cloud/rahti2/storage/volume-snapshot/

## Checklist before requesting a review

- [x] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [x] My pull request passes the automated tests. (If not, visit [pull requests at Travis CI](https://app.travis-ci.com/github/CSCfi/csc-user-guide/pull_requests) and have a look at the job log.)
- [x] I have included a link to the appropriate [preview page](https://csc-guide-preview.rahtiapp.fi/origin/) (select your branch from the list).

2024-07-08 13:03 UTC, jemaltahir reviewed
Checkout the path it is under 
![image](https://github.com/CSCfi/csc-user-guide/assets/51382410/c0c9045e-0fbb-45ad-b0b3-8b28c76fff69)
but supposed to be under like this:
![image](https://github.com/CSCfi/csc-user-guide/assets/51382410/511d108c-dad8-47a1-853f-bae958535afb)

2024-07-08 13:15 UTC, vartikashah commented on docs/cloud/rahti2/storage/VolumeSnapshot.md
done

2024-07-08 13:40 UTC, jemaltahir commented on docs/cloud/rahti2/storage/VolumeSnapshot.md
Could you add a use case by deploying an Nginx application, creating content, taking a snapshot, and then restoring from that snapshot ?

2024-07-12 08:47 UTC, jemaltahir requested changes
Have a look at the comments.

2024-07-12 08:47 UTC, jemaltahir commented on docs/cloud/rahti2/storage/index.md
> +A snapshot represents the state of the storage volume in a cluster at a particular point in time. Volume snapshots can be used to provision a new volume. Volume snapshots help protect against data lo
```suggestion
A snapshot represents the state of the storage volume within a cluster at a specific point in time. Volume snapshots can be used to provision new volume and help protect against data loss in OKD. Rahti2 support Container Storage Interface (CSI) volume snapshots by default and the default volume snapshot class name is standard-csi.
```

2024-07-12 08:47 UTC, jemaltahir commented on docs/cloud/rahti2/storage/index.md
> +You can find additional information on the [Volume snapshot](volume-snapshot.md) page.
```suggestion
- Use volume snapshots as building blocks for developing application-level or cluster-level storage backup solutions.
- Rapidly rollback to a previous version during development.
- Use storage more efficiently by avoiding the need to create a full copy each time.

You can find additional information on the [Volume snapshot](volume-snapshot.md) page.
```

2024-07-12 08:47 UTC, jemaltahir commented on docs/cloud/rahti2/storage/volume-snapshot.md
> +There are two ways to provision snapshots in Rahti2: by web interface and by using CLI.
```suggestion
Rahti2 offers two methods for provisioning snapshots: through the web interface and by using the CLI.
```

2024-07-12 08:47 UTC, jemaltahir commented on docs/cloud/rahti2/storage/volume-snapshot.md
> +- No pods are using persistent volume claim (PVC) that you want to take a snapshot of.
```suggestion
- Ensure no pods are using persistent volume claim (PVC) that you want to take a snapshot of.
```

2024-07-12 08:47 UTC, jemaltahir commented on docs/cloud/rahti2/storage/volume-snapshot.md
> +After making sure that PVC is not attached to any pod, create a volume snapshot by clicking on 'Create VolumeSnapshot' in 'VolumeSnapshot'.
```suggestion
After making sure that PVC is not attached to any pod. Navigate to the 'VolumeSnapshot' section and click on 'Create VolumeSnapshot' to create a snapshot of your PVC. 
```

2024-07-12 08:47 UTC, jemaltahir commented on docs/cloud/rahti2/storage/volume-snapshot.md
> +To list all the volume snapshots, use the command:
Before list , it is good to show how to deploy the  snapshot.yaml? `oc apply -f  snapshot.yaml`

2024-07-12 12:21 UTC, closed without merging