add qiskit on LUMI version
CSCfi/csc-user-guide pull request #2181
Opened 2024-07-29 15:50 UTC by TheKharleeci

## Proposed changes

- add qiskit on LUMI
- update script for quantum job example

Briefly describe the changes you've made here. Remember to add a link to the [preview page](https://csc-guide-preview.2.rahtiapp.fi/origin/) of your branch.

## Checklist before requesting a review

- [x] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [x] My pull request passes the automated tests. If not, visit [pull requests at Travis CI](https://app.travis-ci.com/github/CSCfi/csc-user-guide/pull_requests) and have a look at the job log.
- [x] I have included a link to the appropriate [preview page](https://csc-guide-preview.2.rahtiapp.fi/origin/ft-add-qiskit-on-lumi/).

2024-07-29 17:12 UTC, JMuff22 requested changes

2024-07-29 17:12 UTC, JMuff22 commented on docs/apps/qiskit.md
> +CUDA-accelerated simulation methods. The `qiskit/1.0.2` and `qiskit/1.1.1` packages include the following qiskit plugins:
Perhaps just say "GPU accelerated" and remove specific mention to cuda as we have LUMI now?

2024-07-29 17:12 UTC, JMuff22 commented on docs/apps/qiskit.md
> +The Qiskit module can also be used from the Puhti/LUMI web interface using Jupyter and
```suggestion
The Qiskit module can also be used from Puhti, Mahti and LUMI web interfaces using Jupyter and
```

2024-08-12 10:53 UTC, JMuff22 approved these changes

2024-08-12 11:06 UTC, olmuk approved these changes

2024-08-13 05:34 UTC, merged