Fix: Add advanced page, before it was empty
CSCfi/csc-user-guide pull request #2217
Opened 2024-08-21 09:11 UTC by lvarin

## Proposed changes

Briefly describe the changes you've made here. Remember to add a link to the [preview page](https://csc-guide-preview.2.rahtiapp.fi/origin/pouta-advanced/) of your branch.

## Checklist before requesting a review

- [ ] I have followed the instructions in the [Contributing](https://github.com/CSCfi/csc-user-guide/blob/master/CONTRIBUTING.md) and [Styleguide](https://github.com/CSCfi/csc-user-guide/blob/master/STYLEGUIDE.md) documents.
- [ ] My pull request passes the automated tests. If not, visit [pull requests at Travis CI](https://app.travis-ci.com/github/CSCfi/csc-user-guide/pull_requests) and have a look at the job log.
- [ ] I have included a link to the appropriate [preview page](https://csc-guide-preview.2.rahtiapp.fi/origin/pouta-advanced/) (select your branch from the list).

2024-08-21 10:24 UTC, joonas-somero requested changes
Please use MkDocs format with internal links. https://www.mkdocs.org/user-guide/writing-your-docs/#internal-links

2024-08-27 08:54 UTC, lvarin commented
fixed

2024-08-27 11:51 UTC, trispera approved these changes

2024-08-28 05:04 UTC, joonas-somero approved these changes

2024-08-28 05:06 UTC, merged