Kkmattil local sacratch faq
CSCfi/csc-user-guide pull request #796
Opened 2020-12-10 08:08 UTC by kkmattil

Local scratch FAQ tropic.

2020-12-10 08:39 UTC, yetulaxman approved these changes

2020-12-10 15:32 UTC, amsaren requested changes

2020-12-10 15:32 UTC, amsaren commented on docs/support/faq/local_scratch_for_data_processing.md
> +In this example about 52000 fasta files where found so after the processing the big_data directory contains 52000 more small files.
```suggestion
In this example about 52000 fasta files were found, so after the processing the big_data directory contains 52000 more small files. 
```

2020-12-10 15:32 UTC, amsaren commented on docs/support/faq/local_scratch_for_data_processing.md
> +**Step 3**. When the processing is finished we store the results back to scratch directory into a new tar file to the normal scratch directory
```suggestion
**Step 3**. When the processing is finished we store the results back to scratch directory into a new tar file.
```

2020-12-10 15:32 UTC, amsaren commented on docs/support/faq/local_scratch_for_data_processing.md
> +Now the results are in safe in one file in scratch directory and we can exit from the interactive session.
```suggestion
Now the results are safe in one file in scratch directory and we can exit from the interactive session.
```

2020-12-10 15:32 UTC, amsaren commented on docs/support/faq/local_scratch_for_data_processing.md
> +above in LOCAL_SCRATCH and in normal scratch.  The response times of LOCAL_SCRATCH are be rather stable, but in the scratch directory
```suggestion
above in LOCAL_SCRATCH and in normal scratch.  The response times of LOCAL_SCRATCH are rather stable, but in the scratch directory 
```

2020-12-10 15:32 UTC, amsaren commented on docs/support/faq/local_scratch_for_data_processing.md
> +To demonstrate the effectivity of local scratch area let’s study a sample directory called *big_data*. The directory contains about 100 GiB of data in 120 000 files. In the beginning the data is peak
```suggestion
To demonstrate the effectivity of local scratch area let’s study a sample directory called *big_data*. The directory contains about 100 GiB of data in 120 000 files. In the beginning the data is packed in one tar-archive file in the scratch directory of project 2001234 (/scratch/project_2001234/big_data.tar)
```

2020-12-10 17:07 UTC, kkmattil commented
Korjattu. Kiitos,

2020-12-14 07:40 UTC, amsaren approved these changes

2020-12-14 07:41 UTC, merged