Add explanation for inline Dockerfile
CSCfi/csc-user-guide pull request #856
Opened 2021-02-09 10:08 UTC by lvarin

It just give the command to create build in Rahti with a Dockerfile provided in the command itself

2021-03-15 14:31 UTC, tdeneke requested changes

2021-03-15 14:31 UTC, tdeneke commented on docs/cloud/rahti/images/creating.md
> +It is possible to create a new build using a Dockerfile provided in the command line. By doing this, the `Dockerfile` itself will be embedded in the Build object, so there is no need for an external
```suggestion
It is possible to create a new build using a Dockerfile provided in the command line. By doing this, the `Dockerfile` itself will be embedded in the Build object, so there is no need for an external Git repository.
```

2021-03-15 16:06 UTC, attesillanpaa approved these changes

2021-03-16 06:37 UTC, tdeneke approved these changes

2021-03-16 06:38 UTC, merged